POST http://localhost:5200/user/api
Content-Type: application/json

{
    "firstName": "tri",
    "lastName": "nguyen",
    "gender": "male",
    "bdate": "2001-04-04",
    "email": "nguyentri.alan@gmail.com",
    "phone": "12121",
    "password": "123",
    "role": true
}


###
POST http://localhost:5200/account/auth
Content-Type: application/json

{
    "email": "nguyentri.alan@gmail.com",
    "password": "456"
}


###
GET http://localhost:5200/user/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MzMzYTFjMGFjZjdlNTFlZjViYWM1ZmIifQ.m8iLvIaNZE9hFCa7DqFilOr_diLVuKVDaJoBbIfmvBU



###
PUT http://localhost:5200/account/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MzMzYTFjMGFjZjdlNTFlZjViYWM1ZmIifQ.m8iLvIaNZE9hFCa7DqFilOr_diLVuKVDaJoBbIfmvBU

{
    "oldPassword": "123",
    "newPassword": "456"
}


###
POST http://localhost:5200/channel/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MzMzYTFjMGFjZjdlNTFlZjViYWM1ZmIifQ.m8iLvIaNZE9hFCa7DqFilOr_diLVuKVDaJoBbIfmvBU