POST http://localhost:5200/user/api
Content-Type: application/json

{
    "firstName": "triz",
    "lastName": "nguyen",
    "gender": "male",
    "bdate": "2001-04-04",
    "email": "nguyentri12.alan@gmail.com",
    "phone": "12121",
    "password": "123",
    "role": true
}


###
POST http://localhost:5200/account/auth
Content-Type: application/json

{
    "email": "nguyentri.alan@gmail.com",
    "password": "456"
}


###
GET http://localhost:5200/user/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MzMxNWZlODA0OTIzZjA5ZTgyZmNhMmMifQ.stXcEokUJ7NbtkUhFta2zQ0OiAAYuyjrpPMxesmyLec



###
PUT http://localhost:5200/account/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MzMxMjgyODc0ZjU2YjQ1MzI2YmVlOTkifQ.PUdNo9_D8YVbkmvQZbIXx4R-5Zw8IQwtTSip0ZRr6tc

{
    "oldPassword": "123",
    "newPassword": "456"
}
